import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — LocalBeacon.ai",
  description: "Terms and conditions for using LocalBeacon.ai.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      <nav className="border-b border-white/10 px-6 py-4">
        <div className="max-w-3xl mx-auto">
          <Link href="/" className="flex items-center gap-2">
            <span className="text-2xl">🔦</span>
            <span className="text-xl font-bold text-[#FFD700]">LocalBeacon.ai</span>
          </Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-8">Last updated: March 1, 2026</p>

        <div className="space-y-8 text-white/70 text-sm leading-relaxed">
          <section>
            <h2 className="text-white font-semibold text-lg mb-3">1. Agreement</h2>
            <p>By using LocalBeacon.ai (&quot;the Service&quot;), you agree to these Terms of Service. The Service is operated by Perpetual Agility LLC (&quot;we,&quot; &quot;us,&quot; &quot;LocalBeacon&quot;). If you don&apos;t agree, don&apos;t use the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">2. The Service</h2>
            <p>LocalBeacon is an local marketing platform that helps businesses manage their online visibility. We provide:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Content for Google Business Profiles (posts, updates)</li>
              <li>Local service area page generation</li>
              <li>Review responses</li>
              <li>Local visibility tracking and reporting</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">3. Accounts</h2>
            <p>You must create an account to use LocalBeacon. You are responsible for maintaining the security of your account and all activity under it. You must be at least 18 years old. You must provide accurate business information.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">4. Plans & Billing</h2>
            <p className="mb-2">We offer three plans:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong className="text-white">Free ($0/month):</strong> 1 location, 5 posts/month, 3 city pages</li>
              <li><strong className="text-white">Solo ($49/month):</strong> 3 locations, unlimited posts, 10 city pages, review replies, monthly report</li>
              <li><strong className="text-white">Agency ($99/month):</strong> Unlimited locations, white-label reports, multi-client dashboard, competitor monitoring</li>
            </ul>
            <p className="mt-3">Paid plans are billed monthly through Stripe. You can cancel anytime — your plan remains active until the end of the billing period. We do not offer refunds for partial months.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">5. AI-Generated Content</h2>
            <p>Content generated by LocalBeacon is created using AI (Anthropic Claude). While we strive for accuracy and quality:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>You are responsible for reviewing all content before publishing</li>
              <li>AI-generated content may contain errors — review before posting</li>
              <li>You own the content generated for your business</li>
              <li>We do not guarantee any specific ranking, traffic, or revenue results</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">6. Google Business Profile Access</h2>
            <p>When you connect your Google Business Profile, you authorize us to read your business information and post content on your behalf. You can revoke this access at any time through your Google Account settings. You represent that you have the authority to manage the Google Business Profile you connect.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">7. Acceptable Use</h2>
            <p className="mb-2">You agree NOT to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use the Service for businesses you don&apos;t own or have authorization to manage</li>
              <li>Generate spam, misleading content, or fake reviews</li>
              <li>Violate Google&apos;s Business Profile policies</li>
              <li>Resell access to the Service without an Agency plan</li>
              <li>Attempt to reverse-engineer or abuse the AI generation system</li>
              <li>Use the Service for any illegal purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">8. Agency Plan — Client Management</h2>
            <p>If you use the Agency plan to manage client businesses, you represent that you have written authorization from each client to manage their Google Business Profile and generate content on their behalf. You are responsible for ensuring your clients&apos; content complies with Google&apos;s policies.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">9. Limitation of Liability</h2>
            <p>LocalBeacon is provided &quot;as is&quot; without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages. Our total liability is limited to the amount you paid us in the 12 months before the claim. We do not guarantee any specific SEO rankings, search visibility, or business results.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">10. Termination</h2>
            <p>You can cancel your account at any time. We may suspend or terminate your account if you violate these terms. Upon termination, your data will be deleted within 30 days.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">11. Changes</h2>
            <p>We may update these terms from time to time. We will notify you of material changes by email. Continued use of the Service after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">12. Governing Law</h2>
            <p>These terms are governed by the laws of the State of Minnesota. Any disputes will be resolved in the courts of Dakota County, Minnesota.</p>
          </section>

          <section>
            <h2 className="text-white font-semibold text-lg mb-3">13. Contact</h2>
            <p>Questions? Email <a href="mailto:support@localbeacon.ai" className="text-[#FFD700] hover:underline">support@localbeacon.ai</a>.</p>
            <p className="mt-2">Perpetual Agility LLC<br />Burnsville, MN 55337</p>
          </section>
        </div>
      </main>

      <footer className="px-6 py-8 border-t border-white/10">
        <div className="max-w-3xl mx-auto flex items-center justify-between text-white/30 text-xs">
          <Link href="/" className="hover:text-white/50">← Back to LocalBeacon.ai</Link>
          <Link href="/privacy" className="hover:text-white/50">Privacy Policy</Link>
        </div>
      </footer>
    </div>
  );
}
